package com.example.spacechase;

import javafx.animation.PauseTransition;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javafx.scene.media.Media;
import javafx.util.Duration;
import java.io.File;
/**
 * AdvertController is responsible for controlling the
 * advert window generated by the advert.fxml file
 * to be able to display a video specified by the code.
 * @author Daniel Halsall
 * @version 1.0.0
 */
public class AdvertController extends Controller {
    /**
     * variable holing a button object.
     */
    @FXML
    private Button button;
    /**
     * variable holing a file.
     */
    @FXML
    private File file;
    /**
     * variable holing a media object.
     */
    @FXML
    private Media media;
    /**
     * variable holing a mediaView object.
     */
    @FXML
    private MediaView mediaView;
    /**
     * variable holing a mediaPayer object.
     */
    @FXML
    private MediaPlayer mediaPlayer;
    /**
     * integer variable representing the time
     * taken before the button will appear.
     */
    private final int timer = 5;

    /**
     * initialize will run when the window is loaded to play a
     * video and load a button after a determined amount of time.
     * @author Daniel Halsall
     */
    @FXML
    public void initialize() {
        file = new File(
                "src/main/resources/com/example/spacechase/Vid/vid.mp4");
        media = new Media(file.toURI().toString());
        mediaPlayer = new  MediaPlayer(media);
        mediaView.setMediaPlayer(mediaPlayer);
        mediaPlayer.play();
        button.setVisible(false);
        PauseTransition pt = new PauseTransition(Duration.seconds(timer));
        pt.setOnFinished(e -> {
            button.setVisible(true);
        });
        pt.play();
    }


    /**
     * when the button is pressed the main menu is loaded
     * by changing the controller to the mainMenuController.
     * @author Daniel Halsall
     */
    @FXML
    protected void resetLevel() {
        Controller controller = new Controller();
        controller.loadFxml("fxml/levelMenu.fxml");
    }

}
