package com.example.spacechase.controllers;

import com.example.spacechase.models.Level;
import com.example.spacechase.services.SoundEngine;
import com.example.spacechase.utils.Data;
import javafx.animation.PauseTransition;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javafx.scene.media.Media;
import javafx.util.Duration;
import java.io.File;
/**
 * AdvertController is responsible for controlling the
 * advert window generated by the advert.fxml file
 * to be able to display a video specified by the code.
 * @author Daniel Halsall.
 * @version 1.0.1.
 */
public class AdvertController extends Controller {
    /**
     * Integer variable representing the time
     * taken before the button will appear.
     * @see javafx.scene.media.MediaPlayer
     */
    private static final int TIMER = 5;
    /**
     * Variable holing a button object.
     */
    @FXML
    private Button button;
    /**
     * Variable holing a media object.
     */
    @FXML
    private Media media;
    /**
     * Variable holing a mediaView object.
     * @see javafx.scene.media.Media
     */
    @FXML
    private MediaView mediaView;
    /**
     * Variable holing a mediaPayer object.
     * @see javafx.scene.media.MediaView
     */
    @FXML
    private MediaPlayer mediaPlayer;
    /**
     * Start will play a
     * video and load a button after a determined amount of time
     * to restart the level.
     * @param level the current level the player is on.
     */
    public void start(Level level) {
        File file = Data.getFileFromPath("media/ads/ad1.mp4");
        media = new Media(file.toURI().toString());

        mediaPlayer = new MediaPlayer(media);
        mediaPlayer.setVolume(SoundEngine.getMusicVolume());
        mediaPlayer.play();

        mediaView.fitWidthProperty().bind(stage.widthProperty());
        mediaView.fitHeightProperty().bind(stage.heightProperty());
        mediaView.setMediaPlayer(mediaPlayer);
        mediaView.setViewOrder(1);
        mediaView.setVisible(true);

        button.setVisible(false);
        button.setViewOrder(0);

        PauseTransition pt = new PauseTransition(Duration.seconds(TIMER));
        pt.setOnFinished(e -> {
            button.setVisible(true);
            button.setOnMouseClicked(event -> {
                mediaPlayer.stop();
                LevelEndedMenuController controller = (LevelEndedMenuController)
                        loadFxml("fxml/levelEndedMenu.fxml");
                controller.startFailMenu(level);
            });
        });
        pt.play();
    }
}
